default_agent: cityassistant_311_agent_3
agents:
  cityassistant_311_agent_3:
    name: cityassistant_311_agent_3
    entrypoint: C:/Users/snigd/Desktop/311_agentcore/agentcore_311.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::356225522107:role/AgentCoreRuntimeExecutionRole
      execution_role_auto_create: false
      account: '356225522107'
      region: us-east-1
      ecr_repository: 356225522107.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-cityassistant_311_agent_3
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: cityassistant_311_agent_3-38spwz8TKm
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:356225522107:runtime/cityassistant_311_agent_3-38spwz8TKm
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-cityassistant_311_agent_3-builder
      execution_role: arn:aws:iam::356225522107:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-e064ae4be2
      source_bucket: bedrock-agentcore-codebuild-sources-356225522107-us-east-1
    authorizer_configuration: null
    oauth_configuration: null
